// Audio manifest — regenerated by scripts/make-audio.mjs.
// bed: music bed path under video-assets/ (or null to render silent).
// vo: [{ src, from }] voiceover segments, frame-aligned to SCENES.
export const AUDIO = {
  bed: "audio/bed.wav",
  vo: [], // VO placeholder — script lines live in output/SCRIPT_STORYBOARD.md
};
